# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-06-03 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0003_auto_20180601_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='status',
            field=models.CharField(blank=True, choices=[('C', 'Concluído'), ('D', 'Cancelado')], default='', max_length=1, verbose_name='Status'),
        ),
    ]
